services:
  - type: web
    name: jdg-api-stg
    env: docker
    plan: free
    buildCommand: |
      export $(grep -v '^#' docker-compose.yml | grep 'environment' -A 10 | grep -v 'environment' | sed 's/- //g' | xargs)
      docker build -f ./api/Dockerfile ./api
    startCommand: yarn start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
